spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeogida?serverTimezone=UTC
    username: root
    password: wnswk02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
